### ISSUE TITLE
这个东西怎么用能稍微说明一下嘛。。

### ISSUE THREAD

**Issue by code-Yi-9527** [hiliving/ViVideo#1]
小白不知道怎么用求指点

**Comment by hiliving** [comment]
例如你要看爱奇艺，点开爱奇艺到页面，找到要看到电视剧，比如将夜，选要看到剧集，比如第五集，点对应到按钮，等页面刷新完，点击最上面的播放按钮就行了，如果默认线路不能播放，可切换其他线路

另外，建议直接使用superMovie那个项目的apk，那个里面集成了该项目  @bboyyi1990
